# Generated by Django 3.2.4 on 2021-06-11 05:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20210610_1332'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('stats', django.db.models.manager.Manager()),
            ],
        ),
    ]
